### ISSUE TITLE
範例，送資料的方法好像有點錯

### ISSUE THREAD

**Issue by pc0808f** [iamblue/MCSjs#1]
setTimeout(function() {
  myApp.emit('temperature','', ',,'+data.toString()); 這樣才對
}, 5000)
主要是在傳送的時候，timestamp沒用到，
但目前mcs的mqtt接收方法是用  timestamp, chID, data
但mcsjs的emit，會直接把資料丟出去， 就變成只有 data 而且，所以mcs收不到

**Comment by nalanala** [comment]
我也是苦主，debug花了3小時
Alan

**Comment by iamblue** [comment]
Thanks @pc0808f 

感謝回報，原先 api 在 TCP mode 沒問題， MQTT 則有，因此我剛上了一包修正，請從新 npm install mcsjs (注意版本要到 0.1.4)

BTW, api 設計還是按照原來的一樣:
myApp.emit ('channel', 'timestamp', your data);

Example:
```
var mcs = require('mcsjs');
var myApp = mcs.register({
 deviceId: 'id',
 deviceKey: 'key',
 mqttHost: 'mqtt.mcs.mediatek.com',
 // mqttHost: 'mqtt.mcs.mediatek.cn', //如果是中國 site 的人記得把上一行換成這行.
 method: 'mqtt',
 port: 1883,
 qos: 0,
 // host: 'api.mediatek.cn', // 如果是中國 site 的人記得加這行.
});

myApp.emit('control','', 1231231111);
```
